import Image from 'next/image'
import React from 'react'
import { storiesCircularEconomy } from '@/api/api'
import Slider from '@/components/sliderStories'

export const metadata = {
  title: 'Circular Economy',
  description: 'Circular Economy | SMC Sustainability',
}

export default function Index() {
  return (
    <>

      <h1>Circular Economy </h1>

      <p>The concept of circular economy has been
        part of our culture even before the term
        was mainstreamed. Since establishing a
        circular economy approach is part of our
        topmost sustainability goals, we recognize
        the importance of utilizing our resources
        sustainably, through better efficiency and the
        reduction of waste.</p>

      <p>We recognize that the Company consumes
        a large amount of both renewable and non-renewable resources throughout its various
        business activities. With our continued
        push toward nation building, our demand
        for resources will inevitably increase as the
        Company grows. To address this, we aim to
        transform our business model and to “close the
        loop” in order to shrink our material footprint
        and to prevent any adverse impacts on the
        environment. We have adopted practices of
        reduction, recycling, and recovery, as well as
        developed programs and policies. We strive to
        become more efficient in the materials we use
        and reduce the amount of waste we generate.</p>

      <h3 className='green'>
        Materials and Waste
      </h3>

      <h5 className='brown'>Materials Management</h5>

      <Image style={{ borderRadius: '0' }} src="materials_management.png" width={436} height={201} alt='Materials Management' />

      <p>
        We used 15.7 million MT of materials in 2022
        for our operations. Of this, 65.7% are non-renewable materials and the remaining 34.3%
        are renewable materials. Most material inputs
        were used by Petron and NCC in the form of
        crude oil, limestone, and clinker. We were able
        to recycle 442 thousand MT of the materials we
        used. These recycled items consisted mostly
        of glass bottles retrieved at post-consumer
        stage, for reuse by our beverage businesses, or
        broken glass cullets recycled by our packaging
        business. Also recycled are coal ash from SMGP’s
        power plants used as raw material in the cement
        production process of NCC. In 2022, NCC successfully
        recycled 150,194 MT of coal ash as inputs for cement.
      </p>

      <h3 className='green'>
        We have adopted practices
        of reduction, recycling,
        and recovery, as well as
        developed programs and
        policies. We strive to
        become more efficient
        in the materials we use
        and reduce the amount of
        waste we generate.
      </h3>

      <h5 className='brown'>Solid Waste Management </h5>

      <p>We understand the importance of proper waste
        management to our business operations. The
        Company already has ongoing initiatives designed
        to reduce the amount of waste we generate. We
        accomplish this by finding ways to recirculate byproducts and materials at their highest value.</p>

      <Image style={{ borderRadius: '0' }} src="solid_waste_diverted.png" width={435} height={198} alt='Solid Waste Management' />


      <p>The Company generated 330.6 thousand MT of solid
        waste in 2022, of which we were able to redirect
        approximately 90.3%. Waste classified as spent grain
        and spent yeast, generated by SMFB, has the largest
        contribution to our solid waste. Spent grain and
        spent yeast are protein-rich materials used by our
        animal feeds business, providing nutrients required
        by poultry and livestock for maintenance, growth, and
        reproduction. </p>

      <p>The second largest contributors were glass,
        cullets, and jars used for our bottles and
        beverages, which we were able to reuse or
        recycle. SMB has in place a returnable glass
        bottle system that encourages customers to
        return empty bottles, which the company then
        retrieves from retail outlets. On the other hand,
        GSMI has a robust bottle retrieval system
        through a network of territorial bottle suppliers.
        Recovered bottles are subjected to thorough
        inspection and quality control protocols to
        ensure safety for reuse. Both systems greatly
        reduce the need to manufacture new bottles,
        minimizing product cost and conserving
        material resources. </p>

      <p>Meanwhile, sludge and slop from wastewater
        treatment facilities, and manure from SMF’s
        poultry and pig farms are converted to organic
        fertilizer. Metal scraps, plastic waste and other
        non-hazardous waste that cannot be used in our
        operations are sold to recyclers. The remaining
        solid waste that could not be recycled is sent to
        landfills.</p>

      <p>The Company is prepared to be fully compliant
        with the Republic Act No. 11898, the Extended
        Producer Responsibility (EPR) Act of 2022,
        which became effective on August 13, 2022. The
        law requires obliged enterprises, such as SMFB,
        to recover and divert at least 20% of their 2022
        plastic packaging footprint by the end of 2023
        and increase this annually up to 80% by the end
        of 2028. In future reports, we will be providing
        information on their compliance with EPR.</p>

      <h5 className='brown'>Coal Ash Management </h5>

      <Image style={{ borderRadius: '0' }} src="/page/coal-ash-recycled.png" width={440} height={196} alt='Coal Ash Management' />


      <p>We generated a total of 566.6 thousand MT
        of coal combustion residuals from our power
        generators. We were able to redirect a portion
        of the coal ash and reuse these in our cement
        manufacturing process. The CCR that were
        not reused in our cement plants were sent to
        external companies for further recycling. As
        a result, we were able to recycle 51.6% of our
        generated coal ash in 2022. </p>

      <h5 className='brown'>Hazardous Waste Management  </h5>

      <Image style={{ borderRadius: '0' }} src="/page/Compliance-with-laws.png" width={437} height={196} alt='Hazardous Waste Management' />

      <p>The Company generated 8.9 thousand MT of
        hazardous waste in 2022. Our hazardous waste
        is mostly made up of used oil and sludge from
        our vehicles and generators, as well as reactive
        chemical waste from various manufacturing
        processes. We were able to divert 36.2% of our
        total hazardous waste generated.</p>

      <p>Hazardous waste is strictly regulated by
        environmental regulatory agencies. We abide by
        all laws and regulations regarding hazardous
        waste tracking, usage, and disposal. The
        Company has established a hazardous waste
        and solid waste management system that
        monitors the inventory, generation, and disposal
        of waste. Our Pollution Control Officers are
        tasked with data management and ensuring
        governmental compliance.</p>


    </>
  )
}
